{"human"
	{on spawn
		{if not tagged "texmod_set"
			{if rand 0.2 {delay 0.1 {tex_mod ""}}}
			{if rand 0.2 {delay 0.1 {tex_mod "var1"}}}
			{if rand 0.2 {delay 0.1 {tex_mod "var2"}}}
			{if rand 0.2 {delay 0.1 {tex_mod "var3"}}}
			{if rand 0.2 {delay 0.1 {tex_mod "var4"}}}
			{if rand 0.2 {delay 0.1 {tex_mod "var5"}}}
			{if rand 0.2 {delay 0.1 {tex_mod "var6"}}}		
			{if rand 0.2 {delay 0.1 {tex_mod "var7"}}}	
			{if rand 0.2 {delay 0.1 {tex_mod "var8"}}}
		}
	}
}