;AUTOMATIC WEAPONRY
{"m2_m1919a4" ;M1919 Browning Tripod
	 {on spawn
	    {tags add "HMG"}
		{tags add "usa"}
		{tags add "m2_m1919a4"}
	}
}

{"m63_browning"  ;M2HB .50 Cal Tripod
	 {on spawn
	    {tags add "HMG"}
		{tags add "usa"}
		{tags add "m63_browning"}
	}
}

{"m45_maxson"
	 {on spawn
	    {tags add "HMG"}
		{tags add "usa"}
		{tags add "m45_maxson"}
	}
}

{"40_mm_m1"
	 {on spawn
	    {tags add "AAFLAK"}
		{tags add "usa"}
		{tags add "40_mm_m1"}
	}
}

; AT WEAPONRY

{"m40"
	 {on spawn
	    {tags add "light_at_gun"}
		{tags add "recoilless_rifle"}
		{tags add "usa"}
		{tags add "m40"}
	}
}

{"entac"
	 {on spawn
	    {tags add "light_at_gun"}
		{tags add "atgm"}
		{tags add "usa"}
		{tags add "entac"}
	}
}

;ARTILLERY

{"m116_packhow"
	 {on spawn
	    {tags add "artillery"}
		{tags add "usa"}
		{tags add "m116_packhow"}
	}
}

{"m29_mortar"
	 {on spawn
	    {tags add "artillery"}
		{tags add "mortar"}
		{tags add "usa"}
		{tags add "m29_mortar"}
	}
}

{"m30_mortar"
	 {on spawn
	    {tags add "artillery"}
		{tags add "mortar"}
		{tags add "usa"}
		{tags add "m30_mortar"}
	}
}

{"m98_howtar"
	 {on spawn
	    {tags add "artillery"}
		{tags add "mortar"}
		{tags add "usa"}
		{tags add "m98_howtar"}
	}
}

{"m101a1"
	 {on spawn
	    {tags add "artillery"}
		{tags add "usa"}
		{tags add "m101a1"}
	}
}

{"m114"
	 {on spawn
	    {tags add "artillery"}
		{tags add "heavy_artillery"}
		{tags add "usa"}
		{tags add "m114"}
	}
}

{"m59_longtom"
	 {on spawn
	    {tags add "artillery"}
		{tags add "heavy_artillery"}
		{tags add "usa"}
		{tags add "m59_longtom"}
	}
}

{"m115"
	 {on spawn
	    {tags add "artillery"}
		{tags add "super_heavy_artillery"}
		{tags add "usa"}
		{tags add "m115"}
	}
}

{"m-28"
	 {on spawn
	    {tags add "artillery"}
		{tags add "super_heavy_artillery"}
		{tags add "nuclear_artillery"}
		{tags add "usa"}
		{tags add "m-28"}
	}
}

;LIGHT VEHICLES

{"m151"
	{on spawn
    	{tags add "wheeled_vehicle"}
		{tags add "usa"}
		{tags add "m151"}
    }
}

{"m151_prc77"
	{on spawn
    	{tags add "wheeled_vehicle"}
		{tags add "usa"}
		{tags add "m151"}
		{tags add "radio_car"}
    }
}

{"m151_m2"
	{on spawn
    	{tags add "wheeled_vehicle"}
		{tags add "usa"}
		{tags add "m151_m2"}
    }
}

{"m151_m1919"
	{on spawn
    	{tags add "wheeled_vehicle"}
		{tags add "usa"}
		{tags add "m151_m1919"}
    }
}

{"dodge_m37"
	{on spawn
    	{tags add "wheeled_vehicle"}
		{tags add "usa"}
		{tags add "dodge_m37"}
		{tags add "transport"}
    }
}

{"dodge_m37_ammo"
	{on spawn
    	{tags add "wheeled_vehicle"}
		{tags add "usa"}
		{tags add "dodge_m37_ammo"}
		{tags add "ammo"}
    }
}

{"dodge_m37_eng"
	{on spawn
    	{tags add "wheeled_vehicle"}
		{tags add "usa"}
		{tags add "dodge_m37_eng"}
		{tags add "engineer"}
    }
}

{"m35"
	{on spawn
    	{tags add "wheeled_vehicle"}
		{tags add "usa"}
		{tags add "m35"}
		{tags add "transport"}
    }
}

{"m35_ammo"
	{on spawn
    	{tags add "wheeled_vehicle"}
		{tags add "usa"}
		{tags add "m35_ammo"}
		{tags add "ammo"}
    }
}

{"m35_arty"
	{on spawn
    	{tags add "wheeled_vehicle"}
		{tags add "usa"}
		{tags add "m35_arty"}
		{tags add "ammo"}
    }
}

{"m35_guntruck"
	{on spawn
    	{tags add "wheeled_vehicle"}
		{tags add "usa"}
		{tags add "m35_guntruck"}
    }
}

{"m416"
	{on spawn
    	{tags add "wheeled_vehicle"}
		{tags add "usa"}
		{tags add "m416"}
		{tags add "trailer"}
    }
}

{"m416_m388"
	{on spawn
    	{tags add "wheeled_vehicle"}
		{tags add "usa"}
		{tags add "m416_m388"}
		{tags add "trailer"}
    }
}

{"cckw353_fuel"
	{on spawn
    	{tags add "wheeled_vehicle"}
		{tags add "usa"}
		{tags add "cckw353_fuel"}
		{tags add "fuel"}
    }
}

; LIGHT TANKS

{"m114a1"
	{on spawn
    	{tags add "light_tank"}
		{tags add "usa"}
		{tags add "m114a1"}
		{tags add "radio_car"}
    }
}

{"m114a2
	{on spawn
    	{tags add "light_tank"}
		{tags add "usa"}
		{tags add "m114a2"}
		{tags add "radio_car"}
    }
}

{"m113a1"
	{on spawn
    	{tags add "light_tank"}
		{tags add "usa"}
		{tags add "m113a1"}
		{tags add "apc"}
		{tags add "transport"}
    }
}

{"m113_acav"
	{on spawn
    	{tags add "light_tank"}
		{tags add "usa"}
		{tags add "m113_acav"}
		{tags add "transport"}
		{tags add "apc"}
		{tags add "ifv"}
    }
}

{"m577"
	{on spawn
    	{tags add "light_tank"}
		{tags add "usa"}
		{tags add "m557"}
		{tags add "radio_car"}
    }
}

{"m24_chaffee"
	{on spawn
    	{tags add "light_tank"}
		{tags add "usa"}
		{tags add "m24_chaffee"}
    }
}

{"m41"
	{on spawn
    	{tags add "light_tank"}
		{tags add "usa"}
		{tags add "m41"}
		{tags add "stabiliser"}
    }
}

{"m42"
	{on spawn
    	{tags add "light_tank"}
		{tags add "usa"}
		{tags add "m42"}
		{tags add "spaag"}
    }
}

{"m551"
	{on spawn
		{tags add "light_tank"}
		{tags add "usa"}
		{tags add "m551"}
		{tags add "atgm"}
    }
}

{"m551_acav"
	{on spawn
    	{tags add "light_tank"}
		{tags add "usa"}
		{tags add "m551_acav"}
    }
}

{"m132_zippo"
	{on spawn
    	{tags add "light_tank"}
		{tags add "usa"}
		{tags add "m132_zippo"}
		{tags add "flame_tank"}
    }
}

{"m113_m40"
	{on spawn
    	{tags add "light_tank"}
		{tags add "usa"}
		{tags add "m113_m40"}
    }
}

{"m113_acav_m40"
	{on spawn
    	{tags add "light_tank"}
		{tags add "usa"}
		{tags add "m113_acav_m40"}
    }
}

{"m163"
	{on spawn
    	{tags add "light_tank"}
		{tags add "usa"}
		{tags add "m163"}
		{tags add "spaag"}
		;{tags add "radar"} ;not an early warning radar, only used for gunlaying
    }
}

; MEDIUM TANKS

{"m4a3e8"
	{on spawn
    	{tags add "medium_tank"}
		{tags add "usa"}
		{tags add "m4a3e8"}
    }
}

{"m26_pershing"
	{on spawn
    	{tags add "medium_tank"}
		{tags add "usa"}
		{tags add "m26_pershing"}
    }
}

{"m46_patton"
	{on spawn
    	{tags add "medium_tank"}
		{tags add "usa"}
		{tags add "m46_patton"}
    }
}

{"m47_patton"
	{on spawn
    	{tags add "medium_tank"}
		{tags add "usa"}
		{tags add "m47_patton"}
    }
}

{"m48_patton"
	{on spawn
    	{tags add "medium_tank"}
		{tags add "usa"}
		{tags add "m48_patton"}
    }
}

{"m48a3"
	{on spawn
    	{tags add "medium_tank"}
		{tags add "usa"}
		{tags add "m48a3"}
    }
}

{"m67_zippo"
	{on spawn
    	{tags add "medium_tank"}
		{tags add "usa"}
		{tags add "m67_zippo"}
		{tags add "flame_tank"}
    }
}

{"m60a1"
	{on spawn
    	{tags add "medium_tank"}
		{tags add "usa"}
		{tags add "m60a1"}
    }
}

{"m728"
	{on spawn
    	{tags add "medium_tank"}
		{tags add "usa"}
		{tags add "m728"}
		{tags add "engineer"}
		{tags add "bulldozer"}
    }
}

;HEAVY TANKS

{"m103"
	{on spawn
    	{tags add "heavy_tank"}
		{tags add "usa"}
		{tags add "m103"}
    }
}

; SPGs

{"m56" ;M56 Scorpion
	{on spawn
    	{tags add "spg"}
		{tags add "usa"}
		{tags add "m56"}
    }
}

{"m50" ;M50 Ontos
	{on spawn
    	{tags add "spg"}
		{tags add "usa"}
		{tags add "m56"}
    }
}

{"m125"
	{on spawn
    	{tags add "spg"}
		{tags add "artillery"}
		{tags add "usa"}
		{tags add "m125"}
    }
}

{"m106"
	{on spawn
    	{tags add "spg"}
		{tags add "artillery"}
		{tags add "usa"}
		{tags add "m106"}
    }
}

{"m107"
	{on spawn
    	{tags add "spg"}
		{tags add "artillery"}
		{tags add "super_heavy_artillery"}
		{tags add "usa"}
		{tags add "m107"}
    }
}

{"m108"
	{on spawn
    	{tags add "spg"}
		{tags add "artillery"}
		{tags add "usa"}
		{tags add "m108"}
    }
}

{"m109"
	{on spawn
    	{tags add "spg"}
		{tags add "artillery"}
		{tags add "heavy_artillery"}
		{tags add "usa"}
		{tags add "m109"}
    }
}

{"m110"
	{on spawn
    	{tags add "spg"}
		{tags add "artillery"}
		{tags add "super_heavy_artillery"}
		{tags add "usa"}
		{tags add "m110"}
    }
}

;_______________________________________________
;|					Aircraft					|
;|______________________________________________|

; 'Fake' Helicopter Airplanes for AI and call-in used

{"uh-1b_airborne"
	{on spawn
    	{tags add "aircraft"}
		{tags add "helicopter"}
		{tags add "uh-1b_airborne"}
	}
}

{"uh-1b_ara_airborne"
	{on spawn
    	{tags add "aircraft"}
		{tags add "helicopter"}
		{tags add "uh-1b_ara_airborne"}
	}
}

{"uh-1b_m22_airborne"
	{on spawn
    	{tags add "aircraft"}
		{tags add "helicopter"}
		{tags add "atgm"}
		{tags add "uh-1b_m22_airborne"}
	}
}

{"uh-1b_maxwell_airborne"
	{on spawn
    	{tags add "aircraft"}
		{tags add "helicopter"}
		{tags add "atgm"}
		{tags add "uh-1b_maxwell_airborne"}
	}
}

; Helicopters

{"uh-1h"
	{on spawn
    	{tags add "aircraft"}
		{tags add "helicopter"}
		{tags add "transport"}
		{tags add "uh-1h"}
	}
}

{"uh-1h_sf"
	{on spawn
    	{tags add "aircraft"}
		{tags add "helicopter"}
		{tags add "transport"}
		{tags add "uh-1h_sf"}
	}
}

{"uh-1b"
	{on spawn
    	{tags add "aircraft"}
		{tags add "helicopter"}
		{tags add "uh-1b"}
	}
}

{"uh-1b_ara"
	{on spawn
    	{tags add "aircraft"}
		{tags add "helicopter"}
		{tags add "uh-1b_ara"}
	}
}

{"uh-1b_m22"
	{on spawn
    	{tags add "aircraft"}
		{tags add "helicopter"}
		{tags add "atgm"}
		{tags add "uh-1b_m22"}
	}
}

{"uh-1b_maxwell"
	{on spawn
    	{tags add "aircraft"}
		{tags add "helicopter"}
		{tags add "atgm"}
		{tags add "uh-1b_maxwell"}
	}
}

{"ch-47_chinook_mg"
	{on spawn
    	{tags add "aircraft"}
		{tags add "helicopter"}
		{tags add "transport"}
		{tags add "ammo"}
		{tags add "ch-47_chinook_mg"}
	}
}