(define "items_light_ger"

;// pistol

;// smg
	{item "mp40"					"ammo" 32 {value 2}}

;// mg
	{item "mgun_ger" "belt" "ap"	"ammo" 50 {value 5}}
	{item "mgun_ger" "belt" "ap2"	"ammo" 50 {value 5}}
	{item "mgun_ger" "belt"			"ammo" 50 {value 5}}
	{item "mgun_ger" "mg13"			"ammo" 50 {value 5}}
	{item "mgun_ger" "drum"			"ammo" 50 {value 5}}
	{item "mgun_ger" "doubledrum"	"ammo" 50 {value 5}}
	{item "mgun_ger" "doubledrum" "ap" "ammo" 50 {value 5}}
	{item "mgun_ger" "doubledrum" "ap2" "ammo" 50 {value 5}}

;// rifle
	{item "atrifle_ger"				"ammo" 5  {value 5}}
	{item "rifle_ger" "clip"		"ammo" 10 {value 2}}
	{item "rifle_ger" "gewehr"		"ammo" 10 {value 2}}
	{item "stg44"					"ammo" 30 {value 2}}
	{item "fg42"					"ammo" 20 {value 2}}

;// AT
	{item "k98_antitank"			"ammo" 1  {value 5}}
	{item "k98_grenade"	"he"		"ammo" 1  {value 5}}
	{item "k98_grenade"	"heat"		"ammo" 1  {value 5}}
	{item "k98_grenade"	"heata"		"ammo" 1  {value 5}}
	{item "panzershreck"			"ammo" 1  {value 10}}

;// Light weaponry
	{item "mortarger_80" "he"		"ammo" 1  {value 5}}
	{item "mortarger_80" "sm"		"ammo" 1  {value 5}}
	{item "mortarger_100" "he"		"ammo" 1  {value 5}}
	{item "mortarger_100" "sm"		"ammo" 1  {value 5}}
	{item "mortarger_120" "he"		"ammo" 1  {value 15}}

;// Grenade
	{item "grenade" "m24"					1  {value 5}}
	{item "grenade" "m24_splinter"			1  {value 5}}

	{item "grenade" "m24_geballteladung"	1  {value 10}}
	{item "grenade" "hafthohlladung"		1  {value 10}}
	{item "grenade" "pwm_l"					1  {value 10}}
	{item "grenade" "molotov_cocktail"		1  {value 10}}

	{item "grenade" "m24_smoke"				1  {value 5}}
	{item "grenade" "nbk39"					1  {value 5}}
)

(define "items_light_rus"

;// pistol
	{item "tt33"					"ammo" 16 {value 1}}
	{item "revolver_clip"			"ammo" 14 {value 1}}

;// smg
	{item "ppd_drum"				"ammo" 71 {value 4}}
	{item "pps_stick"				"ammo" 35 {value 2}}
	{item "ppsh_drum"				"ammo" 71 {value 4}}
	{item "ppsh_stick"				"ammo" 35 {value 2}}

;// mg
	{item "hmgun_rus" "ap"			"ammo" 50 {value 5}}
	{item "hmgun_rus" "api"			"ammo" 50 {value 5}}
	{item "mgun_rus" "dp"			"ammo" 47 {value 5}}
	{item "mgun_rus" "dt"			"ammo" 63 {value 5}}
	{item "mgun_rus" "belt"			"ammo" 50 {value 5}}

;// rifle
	{item "atrifle_rus"				"ammo" 5  {value 5}}
	{item "rifle_rus" "clip"		"ammo" 10 {value 2}}
	{item "rifle_rus" "svt"			"ammo" 10 {value 2}}
	{item "shotgun"					"ammo" 10 {value 2}}

;// AT
	{item "dyakonov"				"ammo" 1  {value 5}}
	{item "vpgs41"					"ammo" 1  {value 5}}
	{item "bazooka"					"ammo" 1  {value 10}}

;// Light weaponry
	{item "mortarrus_50" "he"		"ammo" 1  {value 5}}
	{item "mortarrus_82" "he"		"ammo" 1  {value 10}}
	{item "mortarrus_82" "sm"		"ammo" 1  {value 5}}
	{item "mortarrus_120" "he"		"ammo" 1  {value 15}}
	{item "mortarrus_120" "sm"		"ammo" 1  {value 5}}
	{item "mortarrus_120" "ic"		"ammo" 1  {value 10}}

;// Grenade
	{item "grenade" "f1" 					1  {value 5}}
	{item "grenade" "rgd33" 				1  {value 5}}

	{item "grenade" "rpg40"					1  {value 10}}
	{item "grenade" "rpg43"					1  {value 10}}
	{item "grenade" "molotov_cocktail"		1  {value 10}}

	{item "grenade" "rdg1_smoke" 			1  {value 5}}
)



(define "items_light_eng"

;// mg
	{item "mgun_ger" "belt" "mk2"	"ammo" 50 {value 5}}
	
;// rifle
	{item "atrifle_eng"	"ap"		"ammo" 5  {value 5}}
	{item "atrifle_eng"	"ap2"		"ammo" 5  {value 5}}

;// Light weaponry
	{item "mortareng_50" "sm"		"ammo" 1  {value 5}}
	{item "mortareng_50" "wp"		"ammo" 1  {value 5}}

;// Grenade
	{item "grenade" "no8_smoke" 			1  {value 5}}
)

(define "items_light_usa"
;// mg
	{item "hmgun_usa"				"ammo" 50 {value 5}}
	{item "mgun_usa" "belt"			"ammo" 50 {value 5}}
)


(define "items_light_fin"

;// smg
	{item "suomi_drum"				"ammo" 72 {value 4}}
	{item "suomi_stick"				"ammo" 50 {value 3}}
	{item "bergmann_stick"			"ammo" 50 {value 3}}

;// mg
	{item "chauchat"				"ammo" 20 {value 2}}
	{item "m26"						"ammo" 20 {value 2}}
	{item "madsen"					"ammo" 30 {value 3}}


;// Light weaponry
	{item "mortarfin_81" "he"		"ammo" 1  {value 5}}
	{item "mortarfin_81" "sm"		"ammo" 1  {value 5}}
	{item "mortarfin_120" "he"		"ammo" 1  {value 10}}

;// Grenade
	{item "grenade" "m32"					1  {value 5}}
	{item "grenade" "m32_stick"				1  {value 5}}
	{item "grenade" "m36"					1  {value 5}}

	{item "grenade" "m32_satchel"			1  {value 10}}
	{item "grenade" "molotov_bundle_fin"	1  {value 10}}
	{item "grenade" "molotov_cocktail_fin"	1  {value 10}}

	{item "grenade" "m42_wp"				1  {value 5}}
	{item "grenade" "m43_smoke"				1  {value 5}}
)


(define "items_light_generic"
;// flame
	{item "flame_thrower"			"ammo" 50 {value 10}}

;// pistol
	{item "pistol"					"ammo" 20 {value 1}}

;// other
	{item "bandage_ger"						1 {value 1}}
	{item "bandage_rus"						1 {value 1}}
	{item "bandage_fin"						1 {value 1}}
)

(define "items_medic"
;// other
	{item "bandage_ger"						1 {value 1}}
	{item "bandage_rus"						1 {value 1}}
	{item "bandage_fin"						1 {value 1}}
)

(define "items_heavy_ger"
	{item "bullet_20_auto"		"aphe"		"ammo" 20 {value 5}}

	{item "bulletger_20_auto"	"ap"		"ammo" 20 {value 5}}
	{item "bulletger_20_auto"	"apcr"		"ammo" 20 {value 10}}
	{item "bulletger_20_auto"	"he"		"ammo" 20 {value 5}}

	{item "bulletger_30_auto"	"apcr"		"ammo" 20 {value 5}}
	{item "bulletger_30_auto"	"he"		"ammo" 20 {value 5}}

	{item "bulletger_37_auto"	"ap"		"ammo" 10 {value 5}}
	{item "bulletger_37_auto"	"he"		"ammo" 10 {value 5}}

	{item "bulletger_25"		"ap"		"ammo" 3 {value 5}}

	{item "bulletger_28"		"apcr"		"ammo" 1 {value 10}}
	{item "bulletger_28"		"he"		"ammo" 2 {value 5}}

	{item "bulletger_37"		"aphe"		"ammo" 2 {value 5}}
	{item "bulletger_37"		"apcr"		"ammo" 1 {value 10}}
	{item "bulletger_37"		"he"		"ammo" 2 {value 5}}
	{item "bulletger_37"		"heat"		"ammo" 1 {value 10}}

	{item "bullet_37x149" "ger"	"apc"		"ammo" 2 {value 5}}
	{item "bullet_37x149" "ger"	"he"		"ammo" 2 {value 5}}

	{item "bulletger_47"		"apche"		"ammo" 2 {value 5}}
	{item "bulletger_47"		"apcr"		"ammo" 1 {value 10}}
	{item "bulletger_47"		"he"		"ammo" 2 {value 5}}

	{item "bullet_47x193" "ger"	"apc"		"ammo" 2 {value 5}}
	{item "bullet_47x193" "ger"	"he"		"ammo" 2 {value 5}}

	{item "bulletger_50_l42"	"apche"		"ammo" 2 {value 5}}
	{item "bulletger_50_l42"	"apcr"		"ammo" 1 {value 10}}
	{item "bulletger_50_l42"	"he"		"ammo" 2 {value 5}}

	{item "bulletger_50_l60"	"apche"		"ammo" 1 {value 5}}
	{item "bulletger_50_l60"	"apcr"		"ammo" 1 {value 10}}
	{item "bulletger_50_l60"	"he"		"ammo" 1 {value 5}}
	{item "bulletger_50_l60"	"heat"		"ammo" 1 {value 10}}

	{item "bulletger_50_l87"	"apcbche"	"ammo" 1 {value 5}}
	{item "bulletger_50_l87"	"he"		"ammo" 1 {value 5}}

	{item "bullet_75x241" "ger"	"aphe"		"ammo" 1 {value 5}}
	{item "bullet_75x241" "ger"	"he"		"ammo" 1 {value 5}}

	{item "bulletger_75_l24"	"apcbche"	"ammo" 1 {value 5}}
	{item "bulletger_75_l24"	"he"		"ammo" 1 {value 5}}
	{item "bulletger_75_l24"	"heat"		"ammo" 1 {value 10}}
	{item "bulletger_75_l24"	"heata"		"ammo" 1 {value 10}}
	{item "bulletger_75_l24"	"heatb"		"ammo" 1 {value 10}}
	{item "bulletger_75_l24"	"heatc"		"ammo" 1 {value 10}}
	{item "bulletger_75_l24"	"sm"		"ammo" 1 {value 5}}

	{item "bulletger_75_l43"	"apcbche"	"ammo" 1 {value 5}}
	{item "bulletger_75_l43"	"apcr"		"ammo" 1 {value 10}}
	{item "bulletger_75_l43"	"he"		"ammo" 1 {value 5}}
	{item "bulletger_75_l43"	"heat"		"ammo" 1 {value 10}}
	{item "bulletger_75_l43"	"heatb"		"ammo" 1 {value 10}}
	{item "bulletger_75_l43"	"heatc"		"ammo" 1 {value 10}}

	{item "bulletger_75_l70"	"apcbche"	"ammo" 1 {value 5}}
	{item "bulletger_75_l70"	"apcr"		"ammo" 1 {value 10}}
	{item "bulletger_75_l70"	"he"		"ammo" 1 {value 5}}

	{item "bulletger_88_l56"	"apcbche"	"ammo" 1 {value 5}}
	{item "bulletger_88_l56"	"apcr"		"ammo" 1 {value 10}}
	{item "bulletger_88_l56"	"he"		"ammo" 1 {value 5}}
	{item "bulletger_88_l56"	"heat"		"ammo" 1 {value 10}}

	{item "bulletger_88_l71"	"apcbche"	"ammo" 1 {value 5}}
	{item "bulletger_88_l71"	"he"		"ammo" 1 {value 5}}

	{item "bulletger_105"		"aphe"		"ammo" 1 {value 5}}
	{item "bulletger_105"		"he"		"ammo" 1 {value 15}}
	{item "bulletger_105"		"he2"		"ammo" 1 {value 5}}
	{item "bulletger_105"		"heat"		"ammo" 1 {value 10}}

	{item "bulletger_128"		"apcbche"	"ammo" 1 {value 5}}
	{item "bulletger_128"		"he"		"ammo" 1 {value 5}}

	{item "bulletger_150_l11"	"heat"		"ammo" 1 {value 50}}
	{item "bulletger_150_l11"	"he"		"ammo" 1 {value 50}}


	{item "bulletger_150_l30"	"he"		"ammo" 1 {value 50}}
	{item "bulletger_150_l30"	"heat"		"ammo" 1 {value 50}}

	{item "bulletger_170"		"he"		"ammo" 1  {value 70}}
	
	{item "mortarger_200"		"he"		"ammo" 1  {value 30}}
	{item "mortarger_200"		"sm"		"ammo" 1  {value 5}}

	{item "bulletger_210"		"he"		"ammo" 1 {value 100}}

	{item "150mm_nebelwerfer"				"ammo" 1 {value 15}}
	{item "210mm_nebelwerfer"				"ammo" 1 {value 35}}
	{item "300mm_nebelwerfer"				"ammo" 1 {value 50}}
	{item "380mm_rw61"						"ammo" 1 {value 100}}

	{item "bulletger_600"		"he"		"ammo" 1 {value 250}}
	{item "bulletger_600"		"he2"		"ammo" 1 {value 225}}
)

(define "items_heavy_rus"
	{item "bullet_20_auto"		"aphe"		"ammo" 20 {value 5}}

	{item "bulletrus_20_auto"	"ap"		"ammo" 20 {value 5}}
	{item "bulletrus_20_auto"	"apcr"		"ammo" 20 {value 10}}
	{item "bulletrus_20_auto"	"he"		"ammo" 20 {value 5}}

	{item "bulletrus_25_auto"	"apbc"		"ammo" 20 {value 5}}
	{item "bulletrus_25_auto"	"he"		"ammo" 20 {value 5}}

	{item "bulletrus_37_auto"	"ap"		"ammo" 10 {value 5}}
	{item "bulletrus_37_auto"	"he"		"ammo" 10 {value 5}}

	{item "bulletrus_37"		"aphe"		"ammo" 2 {value 5}}
	{item "bulletrus_37"		"he"		"ammo" 2 {value 5}}

	{item "bulletrus_45"		"aphebc"	"ammo" 2 {value 5}}
	{item "bulletrus_45"		"apcr"		"ammo" 1 {value 10}}
	{item "bulletrus_45"		"he"		"ammo" 2 {value 5}}

	{item "bulletrus_57"		"aphe"		"ammo" 1 {value 5}}
	{item "bulletrus_57"		"aphebc"	"ammo" 1 {value 5}}
	{item "bulletrus_57"		"apcr"		"ammo" 1 {value 10}}
	{item "bulletrus_57"		"he"		"ammo" 1 {value 5}}

	{item "bulletrus_76"		"aphebc"	"ammo" 1 {value 5}}
	{item "bulletrus_76"		"aphebc2"	"ammo" 1 {value 5}}
	{item "bulletrus_76"		"apcr"		"ammo" 1 {value 10}}
	{item "bulletrus_76"		"heat"		"ammo" 1 {value 10}}
	{item "bulletrus_76"		"he"		"ammo" 1 {value 5}}

	{item "bulletrus_85"		"aphe"		"ammo" 1 {value 5}}
	{item "bulletrus_85"		"aphebc"	"ammo" 1 {value 5}}
	{item "bulletrus_85"		"apcr"		"ammo" 1 {value 10}}
	{item "bulletrus_85"		"he"		"ammo" 1 {value 5}}

	{item "bulletrus_100"		"aphe"		"ammo" 1 {value 5}}
	{item "bulletrus_100"		"aphebc"	"ammo" 1 {value 5}}
	{item "bulletrus_100"		"he"		"ammo" 1 {value 5}}

	{item "bullet_107x442" "rus" "he"		"ammo" 1 {value 15}}

	{item "bullet_122x159" "rus" "he"		"ammo" 1 {value 25}}
	{item "bullet_122x159" "rus" "sm"		"ammo" 1 {value 15}}

	{item "bulletrus_122_l22"	"he"		"ammo" 1 {value 25}}
	{item "bulletrus_122_l22"	"heat"		"ammo" 1 {value 15}}

	{item "bulletrus_122_l48"	"aphe"		"ammo" 1 {value 10}}
	{item "bulletrus_122_l48"	"aphebc"	"ammo" 1 {value 10}}
	{item "bulletrus_122_l48"	"he"		"ammo" 1 {value 15}}

	{item "bulletrus_125"		"ic"		"ammo" 1 {value 10}}

	{item "bulletrus_130"		"aphe"		"ammo" 1 {value 10}}
	{item "bulletrus_130"		"he"		"ammo" 1 {value 10}}

	{item "bulletrus_152"		"aphe"		"ammo" 1 {value 20}}
	{item "bulletrus_152"		"aphebc"	"ammo" 1 {value 20}}
	{item "bulletrus_152"		"he"		"ammo" 1 {value 50}}

	{item "bulletrus_152_l24"	"he"		"ammo" 1 {value 50}}

	{item "bulletrus_152_l47"	"he"		"ammo" 1 {value 50}}

	{item "bulletrus_180"		"he"		"ammo" 1 {value 50}}

	{item "bulletrus_203"		"he"		"ammo" 1 {value 100}}

	{item "bulletrus_280"		"he"		"ammo" 1 {value 250}}

	{item "82mm_rs82"						"ammo" 1 {value 15}}
	{item "132mm_bm13"						"ammo" 1 {value 25}}
	{item "300mm_bm30"						"ammo" 1 {value 50}}
)

(define "items_heavy_eng"
	{item "bulleteng_40"		"ap"		"ammo" 2 {value 5}}
	{item "bulleteng_40"		"apcbc"		"ammo" 2 {value 5}}

	{item "bulleteng_57"		"apcbc"		"ammo" 2 {value 5}}
	{item "bulleteng_57"		"he"		"ammo" 2 {value 5}}

	{item "bullet_57x441" "eng"	"ap"		"ammo" 1 {value 5}}
	{item "bullet_57x441" "eng"	"apc"		"ammo" 1 {value 5}}
	{item "bullet_57x441" "eng"	"apcbc"		"ammo" 1 {value 5}}
	{item "bullet_57x441" "eng"	"apds"		"ammo" 1 {value 5}}
	{item "bullet_57x441" "eng"	"he"		"ammo" 1 {value 5}}

	{item "bulleteng_114"		"he"		"ammo" 1 {value 10}}
)

(define "items_heavy_generic"
	{item "sandbag_vehicle"						1 {value 10}}
)

(define "items_heavy_fin"

	{item "mortarfin_170"		"he"		"ammo" 1  {value 50}}

	{item "bulletfin_20"		"ap"		"ammo" 20 {value 5}}
	{item "bulletfin_20_auto"	"ap"		"ammo" 20 {value 5}}
	{item "bulletfin_20_auto"	"he"		"ammo" 20 {value 5}}

	{item "bullet_20x138b_auto" "fin" "ap"	"ammo" 20 {value 5}}
	{item "bullet_20x138b_auto" "fin" "he"	"ammo" 20 {value 5}}

	{item "bullet_40x331_auto" "fin" "apbc"	"ammo" 10 {value 5}}
	{item "bullet_40x331_auto" "fin" "he"	"ammo" 10 {value 5}}

	{item "bullet_37x94" "fin" "aphe"		"ammo" 2 {value 5}}
	{item "bullet_37x94" "fin" "he"			"ammo" 2 {value 5}}
	{item "bullet_37x257" "fin" "ap"		"ammo" 2 {value 5}}
	{item "bullet_37x257" "fin" "he"		"ammo" 2 {value 5}}

	{item "bullet_47x195" "fin" "aphe"		"ammo" 2 {value 5}}
	{item "bullet_47x195" "fin" "he"		"ammo" 2 {value 5}}

	{item "bullet_75x657" "fin" "apbc"		"ammo" 1 {value 5}}
	{item "bullet_75x657" "fin" "he"		"ammo" 1 {value 5}}

	{item "bullet_84x294" "fin" "ap"		"ammo" 1 {value 5}}
	{item "bullet_84x294" "fin" "he"		"ammo" 1 {value 5}}

	{item "bullet_105x380" "fin" "he"		"ammo" 1 {value 15}}
	{item "bullet_105x764" "he"				"ammo" 1 {value 15}}
	{item "bullet_107x442" "fin" "he"		"ammo" 1 {value 15}}

	{item "bullet_114x86" "fin" "he"		"ammo" 1 {value 5}}
	{item "bullet_114x86" "fin" "heat"		"ammo" 1 {value 10}}

	{item "bullet_120_l27" "fin" "he"		"ammo" 1 {value 25}}

	{item "bullet_122x159" "fin" "he"		"ammo" 1 {value 25}}
	{item "bullet_122x159" "fin" "sm"		"ammo" 1 {value 15}}

	{item "bullet_155_l15" "fin" "he"		"ammo" 1 {value 50}}
	{item "bullet_203_l16" "fin" "he"		"ammo" 1 {value 100}}
)

(define "items_heavy_usa"
	{item "bulletusa_37"		"ap"		"ammo" 2 {value 5}}
	{item "bulletusa_37"		"he"		"ammo" 2 {value 5}}

	{item "bulletusa_75x350"	"ap"		"ammo" 1 {value 5}}
	{item "bulletusa_75x350"	"apcbche"	"ammo" 1 {value 5}}
	{item "bulletusa_75x350"	"he"		"ammo" 1 {value 5}}

	{item "bulletusa_76x539"	"ap"		"ammo" 1 {value 5}}
	{item "bulletusa_76x539"	"apcbche"	"ammo" 1 {value 5}}
	{item "bulletusa_76x539"	"he"		"ammo" 1 {value 5}}
)

(define "items_engineer"
;// fortification tools
	{item "shovel_ger"							1 {value 5}}
	{item "shovel_rus"							1 {value 5}}
	{item "shovel_fin"							1 {value 5}}
	{item "pickaxe"								1 {value 10}}
	{item "tent_kit"							1 {value 5}}
	{item "sandbag_vehicle"						1 {value 10}}

;// general tools
	{item "mine_detector"						1 {value 20}}
	{item "repair_kit"							1 {value 20}}

;// special ammo
	{item "flame_thrower"				"ammo"  10 {value 10}}
)

(define "items_explosives"
;// explosives
	{item "geballteladung_3kg"					1 {value 15}}
	{item "satchel_charge_rus"					1 {value 15}}

;// mines
	{item "s" "mine" 							1 {value 5}}
	{item "pmd" "mine" 							1 {value 5}}

	{item "m39" "mine" 							1 {value 10}}
	{item "tm_35" "mine" 						1 {value 10}}
	{item "tm_41" "mine" 						1 {value 10}}
	{item "tmi_35" "mine" 						1 {value 10}}
	{item "tmi_43" "mine" 						1 {value 10}}
	{item "tmd_b" "mine" 						1 {value 10}}
	{item "tmd_44" "mine" 						1 {value 10}}
)

;/*=================== Item Defines End ===================*/