;{"Allies" 
;	{title "mp/alliance/allies"}
;	{armies "rus"}
;	{icon "/interface/pages/multi/flag_allies"}
;}
;{"Axis"
;	{title "mp/alliance/axis"}
;	{armies "ger"}
;	{armies "fin"}
;	{icon "/interface/pages/multi/flag_axis"}
;}
{"Nato"
	{title "mp/alliance/nato"}
	{armies "usa"}
	{icon "/interface/pages/multi/flag_nato"}
}
{"Warsaw" 
	{title "mp/alliance/warsaw"}
	{armies "sov"}	
	{icon "/interface/pages/multi/flag_warsaw"}
}
;{"Eastpact" 
;	{title "mp/alliance/eastpact"}
;	{armies "sov"}	
;	{icon "/interface/pages/multi/flag_eastpact"}
;}