; SDL


;(include "preset_early.inc")
;(include "preset_user_early.inc")  ;// user selectable set
(include "preset_mid.inc")
;include "preset_user_mid.inc")     ;// user selectable set
;(include "preset_late.inc")
;(include "preset_user_late.inc")   ;// user selectable set

;(include "preset_test_early.inc")   ;//test mode
(include "preset_test_mid.inc")     ;//test mode
;(include "preset_test_late.inc")    ;//test mode
